
sudo: required
dist: trusty
language: node_js
node_js:
- '12'
git:
  depth: 3
script:
- echo "skipping tests"
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/telegram.sh"
  on:
    repo: dmitriym09/test-wsenevts
    branch: master
env:
  global:
    - secure: "bPoPxItW78xSoqAsDEAUgxhwwFXQw10UHc3sGOfF6G5PCxZMeJQLI+/yq5k4xoqD39ifhlQeL2fMUcHrTCO9/JS9eACNKfN30NQw7tSYg/r2uZ8UKpWY2gS2VoGtEPWU+2mW1djBEFAUw11TgBcb4/4Juns3vkN3okNR39pFX76elAKvGSsYb2AGW1UzyHYL+UHWpelYH/Js6pvMWSWdcs03nPm2FO8FnxPABNnWVJvKfWny8o/eawLzYvr9nPAxmo+k7GXjJgANwFJCQM0DBxNjo5814032cd9Nc4CuLDO+w3xxj5OJBqmjK2/U2ILo7d/lkM3lRnp26xRo8l4HxtQYRbOMpSCy9G0DIGNYxtsF1cZcVu2Eba40mKAMObUGWiecNWOYvVQ68FVPmZTtisMxbkoQhCYmE9drxtDqepYKU+kASdWrBY3uL+lWoD/IxAyyCSRMmPSfHPX/6deS+IceE6E3tREVH84qihZtON4dTWmwDUbUP7aDKJygkAdzGHUKqqpd6/d+1fR7I+8S5sUDXRYb1eVWidyN/hxHMk7K/esvLU4uO0a+XqINBvw3tEtoG1e1kt0A32VhBjs4kp69oNJoD1LNtfXRZIu6/pDKoZzBS6lrKRg9fqlMl1wWQtHbZ6/43WDQwz4lG05BWHIAY3UTegHxIe6q1DQRbTQ=" 
