
sudo: required
dist: trusty
language: node_js
node_js:
- '12'
git:
  depth: 3
script:
- echo "skipping tests"
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/telegram.sh"
  on:
    repo: dmitriym09/test-wsenevts
    branch: master
